services:
  incidents-search-service:
    image: ${DOCKER_REGISTRY-}api
    container_name: incidents-search
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on: 
     - elasticsearch
  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
