name: incidents-search

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore IncidentsSearchSolution/IncidentsSearchSolution.sln

    - name: Build
      run: dotnet build IncidentsSearchSolution/IncidentsSearchSolution.sln --configuration Release

    - name: Run tests
      run: dotnet test IncidentsSearchSolution/SearchService.Tests/SearchService.Tests.csproj --configuration Release --no-build
